矩阵链最优括号化方案


In [7]:
import numpy as np
def matrix_chain_order(p):
    n = len(p) - 1
    m = [[0 for _ in range(n)] for _ in range(n)]
    s = [[0 for _ in range(n)] for _ in range(n)]
    for l in range(2, n + 1):
        for i in range(n - l + 1):
            j = i + l - 1
            m[i][j] = float('inf')
            for k in range(i, j):
                q = m[i][k] + m[k + 1][j] + p[i] * p[k + 1] * p[j + 1]
                if q < m[i][j]:
                    m[i][j] = q
                    s[i][j] = k
    return m, s

In [ ]:
# m, s = matrix_chain_order([10, 100, 5, 50])
m, s = matrix_chain_order([5,10,3,12,5,50,6])

# print(m)
# print(s)

# 打印最优括号化方案
def print_optimal_parens(s, i, j):
    if i == j:
        print(f"A{i+1}", end="")
    else:
        print("(", end="")
        print_optimal_parens(s, i, s[i][j])
        print_optimal_parens(s, s[i][j] + 1, j)
        print(")", end="")

print_optimal_parens(s, 0, len(s) - 1)

# 格式化输出二阶矩阵
print("\n",np.array(m))
print("\n",np.array(s))


((A1A2)((A3A4)(A5A6)))
 [[   0  150  330  405 1655 2010]
 [   0    0  360  330 2430 1950]
 [   0    0    0  180  930 1770]
 [   0    0    0    0 3000 1860]
 [   0    0    0    0    0 1500]
 [   0    0    0    0    0    0]]

 [[0 0 1 1 3 1]
 [0 0 1 1 1 1]
 [0 0 0 2 3 3]
 [0 0 0 0 3 3]
 [0 0 0 0 0 4]
 [0 0 0 0 0 0]]


: 